{% set version = "1.3.5" %}

package:
  name: protoc-gen-go
  version: {{ version }}

source:
  url: https://github.com/golang/protobuf/archive/v{{ version }}.tar.gz
  sha256: a3ab705fc75b48cba9ac18d10cb4012416714cc8edaeb151a85c46ac3a65033b
  folder: src/protobuf

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - make

test:
  commands:
    # no --version command exists
    - which protoc-gen-go  # [unix]
    - where protoc-gen-go  # [win]

about:
  home: https://github.com/golang/protobuf
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/protobuf/LICENSE
  summary: Go support for Protocol Buffers - Google's data interchange format

extra:
  recipe-maintainers:
    - hmaarrfk
