{% set version = "1.3.4" %}

package:
  name: protoc-gen-go
  version: {{ version }}

source:
  url: https://github.com/golang/protobuf/archive/v{{ version }}.tar.gz
  sha256: 5e4279eb197ff7271cb06ae97a16f721d0fd6962ff2d2560831309c0900e72c4
  folder: src/protobuf

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - make

test:
  commands:
    # no --version command exists
    - which protoc-gen-go  # [unix]
    - where protoc-gen-go  # [win]

about:
  home: https://github.com/golang/protobuf
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/protobuf/LICENSE
  summary: Go support for Protocol Buffers - Google's data interchange format

extra:
  recipe-maintainers:
    - hmaarrfk
