# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Iq/bcCmVmNb18gL0eFA6o7tXezs2526Mj84bWgFavfhIIcrSenuc5DT42ydgjZ3LOOaVPB59rNQQbhu/m+O3CBIPbPnHInBZ7EvNkMyKn0dHPgyoP3Pt76fApPLdCkkGuBWMES6g/oB4uliD50A1JzDo8p8vG+lbeUP7M7QCpJuTnqF3qmG5dhOAvs/fPvOmPglgZCXwyo4XxfB3LmKBvtlEaiXxSXqZubA3YjkUYL+Y9kouzOPJZ2GKralxThwaQB7xZGA2ynyJf0wYw6XFA3pkmxkcV/EPHdGvVFnM4zJWLDhyADmxdf3WwiuFDrApDQcMTOKibkeZrgPDsp1R8MZkFA1j84vMjw/XL4UDLKkq/UEJf0JdBc4sFEbqeJaC1nHKfmey4/Z+Xo8LFUImyJddlIYF4N+GicoNfD5fCv9HjiL5CB/mqDDpyK0BttW/BjfYbphY6kCAx9rdOKPpquDmMb5s8k9gNd5AqusIeXRMHcBPnjQURdV1Lotz+nQXktmxaP/vZdhDgywmVVVQUQDmOdcqw6R/Q5G1rRnTsp93Pkvo7ne9zvBZTPO1C4TbFY3iL3316FHrYCy2lwZzSMf43lqeXByCIrMsaNaqum3baLDZMPOB8+j8jtrEXy4lVGh+rlKQnQiFblSdhOqsWOM9HqTl81zSD+0iYV6trI4="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi